"""
renderer_v2.render_scene
=========================

Defines ``RenderScene``: the canonical scene graph itself, plus the
stores that hold geometry/material/statistics by reference, and scene-level
bookkeeping (warnings).

A RenderScene owns all RenderNodes for one render job. Nodes reference
each other by id (via ``parent`` / ``children``) rather than holding
direct object references, so the whole scene stays trivially serializable
and there's a single place (this class) responsible for keeping the
parent/child relationship consistent.

PR-2 change: geometry_store / material_store / statistics are now
strongly typed (Dict[str, GeometryData], Dict[str, MaterialData],
SceneStatistics) instead of Dict[str, Any]. This changes to_dict()/
from_dict() for those three fields: they now serialize/deserialize each
entry through its own to_dict()/from_dict() instead of passing raw dict
data through untouched. PR-1 shipped with nothing populating these
stores, so no existing data is affected by this change.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .render_node import RenderNode
from .geometry_data import GeometryData
from .material_data import MaterialData
from .scene_statistics import SceneStatistics


@dataclass
class RenderScene:
    """The V2 scene graph for one render job.

    Fields
    ------
    nodes
        All RenderNodes in this scene, keyed by ``RenderNode.id``. This is
        the graph itself; hierarchy lives inside each node's
        ``parent``/``children`` fields.
    geometry_store
        GeometryData entries keyed by the ids that
        ``RenderNode.geometry_ref`` points at. Multiple nodes can share
        one entry (e.g. instanced furniture) without duplicating vertex
        data.
    material_store
        MaterialData entries keyed by the ids that
        ``RenderNode.material_ref`` points at. Having exactly one place
        materials live is what will let a later PR delete the duplicate
        color-resolution logic currently living in both scene_merger.py
        and aps-pipeline.js.
    metadata_store
        Scene-wide metadata that doesn't belong to any single node (e.g.
        source file paths, IFC schema version). Distinct from a node's own
        ``metadata`` field, which is per-node. Left as Dict[str, Any] --
        PR-2 only scoped typed models for geometry/material/statistics.
    warnings
        Scene-level, unstructured warning strings produced while building
        or mutating the graph (e.g. "node references a parent that
        doesn't exist yet"). Kept intentionally simple here; per-stage,
        structured diagnostics belong in ``SceneReport`` instead -- this
        field is only for bookkeeping generated by RenderScene's own
        methods below.
    statistics
        Strongly typed SceneStatistics for this scene. Not populated
        automatically by RenderScene -- future stages write into it as
        they run.
    """

    nodes: Dict[str, RenderNode] = field(default_factory=dict)
    geometry_store: Dict[str, GeometryData] = field(default_factory=dict)
    material_store: Dict[str, MaterialData] = field(default_factory=dict)
    metadata_store: Dict[str, Any] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)
    statistics: SceneStatistics = field(default_factory=SceneStatistics)

    def add_node(self, node: RenderNode) -> None:
        """Add ``node`` to the scene.

        Raises ``ValueError`` if a node with the same id already exists --
        silently overwriting a node would hide a real bug (e.g. two
        elements resolving to the same id) rather than surface it.

        If ``node.parent`` is set and the parent already exists in the
        scene, this also registers ``node`` as a child of that parent
        (via ``RenderNode.add_child``), so callers don't have to update
        both ends of the relationship themselves. If the parent doesn't
        exist yet (e.g. nodes are being added in a non-hierarchical
        order), a note is appended to ``warnings`` rather than raising --
        the caller may add the parent afterward.
        """
        if node.id in self.nodes:
            raise ValueError(
                f"Cannot add node: id '{node.id}' already exists in this scene."
            )
        self.nodes[node.id] = node
        if node.parent is not None:
            parent_node = self.nodes.get(node.parent)
            if parent_node is not None:
                parent_node.add_child(node.id)
            else:
                self.warnings.append(
                    f"Node '{node.id}' declares parent '{node.parent}', "
                    f"which does not exist in the scene yet."
                )

    def remove_node(self, node_id: str, promote_children: bool = True) -> bool:
        """Remove the node with id ``node_id`` from the scene.

        Returns True if a node was removed, False if no such node existed.

        Handles the two relationships a node can have:
          - Unlinks it from its parent's children list, if it has a parent.
          - For its own children: if ``promote_children`` is True (default),
            each child is re-parented to removed node's former parent (so
            the subtree stays attached to the scene instead of vanishing).
            If False, children are orphaned to the scene root
            (``parent = None``). Either way, a note is appended to
            ``warnings`` describing what happened, since re-parenting a
            subtree is a structural change worth being able to audit.
        """
        node = self.nodes.pop(node_id, None)
        if node is None:
            return False

        if node.parent is not None:
            former_parent = self.nodes.get(node.parent)
            if former_parent is not None:
                former_parent.remove_child(node_id)

        if node.children:
            for child_id in node.children:
                child = self.nodes.get(child_id)
                if child is None:
                    continue
                child.parent = node.parent if promote_children else None
                if promote_children and node.parent is not None:
                    new_parent = self.nodes.get(node.parent)
                    if new_parent is not None:
                        new_parent.add_child(child_id)
            if promote_children:
                self.warnings.append(
                    f"Node '{node_id}' removed; {len(node.children)} "
                    f"child(ren) promoted to parent '{node.parent}'."
                )
            else:
                self.warnings.append(
                    f"Node '{node_id}' removed; {len(node.children)} "
                    f"child(ren) orphaned to scene root."
                )

        return True

    def find_by_global_id(self, global_id: str) -> Optional[RenderNode]:
        """Return the first node whose ``global_id`` matches, or None.

        GlobalIds are unique within a well-formed IFC file, so "first
        match" is expected to also be "only match" in practice.
        """
        for node in self.nodes.values():
            if node.global_id == global_id:
                return node
        return None

    def find_by_instance_id(self, instance_id: str) -> Optional[RenderNode]:
        """Return the first node whose ``instance_id`` matches, or None."""
        for node in self.nodes.values():
            if node.instance_id == instance_id:
                return node
        return None

    def find_by_ifc_type(self, ifc_type: str) -> List[RenderNode]:
        """Return all nodes whose ``ifc_type`` matches exactly.

        Returns a list (possibly empty) since many nodes typically share
        an ifc_type (e.g. every wall is "IfcWallStandardCase").
        """
        return [node for node in self.nodes.values() if node.ifc_type == ifc_type]

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the whole scene to a plain, JSON-safe dict.

        geometry_store/material_store entries are serialized via their
        own to_dict(); statistics via SceneStatistics.to_dict().
        metadata_store is passed through as-is: this PR doesn't define
        its internal schema, so it can't do anything smarter than assume
        the caller only ever puts JSON-serializable data into it.
        """
        return {
            "nodes": {node_id: node.to_dict() for node_id, node in self.nodes.items()},
            "geometry_store": {
                geom_id: geom.to_dict() for geom_id, geom in self.geometry_store.items()
            },
            "material_store": {
                mat_id: mat.to_dict() for mat_id, mat in self.material_store.items()
            },
            "metadata_store": self.metadata_store,
            "warnings": list(self.warnings),
            "statistics": self.statistics.to_dict(),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "RenderScene":
        """Reconstruct a RenderScene from a dict produced by ``to_dict``.

        Nodes are loaded directly into ``self.nodes`` (bypassing
        ``add_node``'s duplicate/missing-parent checks) since the data is
        assumed to already represent a previously-valid scene. If you're
        loading hand-written or otherwise untrusted data, validate it
        separately before calling this.

        geometry_store/material_store entries are reconstructed via
        GeometryData.from_dict()/MaterialData.from_dict(); statistics via
        SceneStatistics.from_dict(). Data written by PR-1 (which had no
        geometry_store/material_store/statistics entries populated at
        all) loads cleanly into empty stores and default statistics.
        """
        scene = cls(
            metadata_store=dict(data.get("metadata_store") or {}),
            warnings=list(data.get("warnings") or []),
            statistics=SceneStatistics.from_dict(data.get("statistics") or {}),
        )
        raw_nodes = data.get("nodes") or {}
        for node_id, node_data in raw_nodes.items():
            scene.nodes[node_id] = RenderNode.from_dict(node_data)

        raw_geometry = data.get("geometry_store") or {}
        for geom_id, geom_data in raw_geometry.items():
            scene.geometry_store[geom_id] = GeometryData.from_dict(geom_data)

        raw_materials = data.get("material_store") or {}
        for mat_id, mat_data in raw_materials.items():
            scene.material_store[mat_id] = MaterialData.from_dict(mat_data)

        return scene