# logic/image_metadata.py
import os
import json
from pathlib import Path
from datetime import datetime

def get_metadata_path(img_path_str, dataset_dir):
    img_path = Path(img_path_str)
    meta_dir = Path(dataset_dir) / "metadata"
    meta_dir.mkdir(parents=True, exist_ok=True)
    return meta_dir / (img_path.stem + ".json")

def metadata_exists(img_path_str, dataset_dir):
    return get_metadata_path(img_path_str, dataset_dir).exists()

def load_metadata(img_path_str, dataset_dir):
    meta_path = get_metadata_path(img_path_str, dataset_dir)
    if meta_path.exists():
        try:
            with open(meta_path, "r") as f:
                return json.load(f)
        except Exception:
            return {}
    return {}

def save_metadata(img_path_str, dataset_dir, data):
    meta_path = get_metadata_path(img_path_str, dataset_dir)
    data["_saved_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(meta_path, "w") as f:
        json.dump(data, f, indent=2)
    return meta_path

def build_metadata_from_ocr(img_path_str, img, ocr_seeds, room_names, label_lines, labelled, img_h, img_w):
    return {
        "source": "ocr",
        "n_labels": len(label_lines),
        "rooms": [],
        "label_counts": {k: len(v) for k, v in labelled.items() if isinstance(v, list)},
        "ifc_classes": {},
        "notes": ""
    }

def build_metadata_from_gemini(img_path_str, gemini_data):
    return {
        "source": "gemini",
        "gemini_data": gemini_data,
        "notes": "Generated by Gemini"
    }

def list_all_metadata(dataset_dir):
    meta_dir = Path(dataset_dir) / "metadata"
    if not meta_dir.exists():
        return []
    
    results = []
    for f in meta_dir.glob("*.json"):
        try:
            with open(f, "r") as file:
                data = json.load(file)
                results.append({
                    "basename": f.stem,
                    "source": data.get("source", "unknown"),
                    "n_labels": data.get("n_labels", 0)
                })
        except:
            pass
    return results